### PR TITLE
WIP: A very broken but RUNNING version of docker

### PR DESCRIPTION
**Pull request by tussennet**
This version of the port of docker is hacked to make it compile. I though it would be worth sharing this state. Maybe you would like to pull this into a separate branch, but I don't think I can create a PR to a non-existing branch.

### CODE REVIEW

**Comment by decke** [comment]
Wow you made a very good progress on that! I will merge this right away since this repository is for development only - so nobody will complain.

Thanks a lot!

**Comment by decke** [comment]
If you want a separate branch for your docker work just let me know.

**Comment by tussennet** [comment]
I am not really in need of a separate branch, I can do all versioning on my own fork. The reason I suggested a separate branch was to create distinction between my hack-work and actual implementation work, but I guess all the patches should be reviewed anyway.  

BTW suggestions on how to port broken features are welcome, I am quite a noob regarding freebsd/go/docker development.

**Comment by decke** [comment]
Back when I started the work the plan was roughly:

1) start with a new port based on moby (done)
2) hack it to get it compile (done)
3) integrate containerd and runC (see bottom of TODO)
4) runtime testing
5) cleanup patches / upstreaming

I plan  to update the port to the latest patchlevel 19.03.12 and fix building on poudriere if I find some time.

**Comment by tussennet** [comment]
Do you have any plan for updating the port to the latest patchlevel? because this could possibly interfer with anything I would do.

And do you know what version of containerd en runC is currently in the vendor folder? This would be easier for diff reference.

**Comment by decke** [comment]
Yeah, I planned to update the port to 19.03.12 but it probably makes more sense if you do - to avoid interference. Here's how:

- change version in ports Makefile to 19.03.12
- make makesum
- fix any fallout / regenerate patches as needed

**Comment by decke** [comment]
The contents of the vendor folder is described in vendor.conf:

https://github.com/docker/engine/blob/master/vendor.conf

**Comment by tussennet** [comment]
Thanks the update to the lastest version seems like something I can do :)

Last time I tried updating containerd/runc but for both it seems that it's more than a matter of copy pasting the contents of a specific commit. A lot of extra files seem to be added that have been in the their original repository for a long time. Maybe I am doing something wrong. Any help is welcome.

I have also been doing a little work into getting the port to actually install and trying to get the normal docker port to connect to the docker deamon but has been unsuccesfull till now. All I managed to find thusfar is a comment piece of code for do-install in the old docker-freebsd: https://github.com/decke/ports/blob/master/sysutils/docker-freebsd/Makefile

**Comment by tussennet** [comment]
I have containerd working with dockerd in a basic form, runc is up next (and there will be alot of hacks that have to be removed). I am wondering how the containerd and runc binaries are going to be distributed with ports. Should they get there own ports or should we get them inside the docker-engine port? How does this work?

**Comment by decke** [comment]
Both is possible. If the binaries are really independent then it makes sense to have separate ports for them. If all 3 are build from one source or are somehow interconnected then it is usually easier to keep them together in one port.

**Pull request merged**
