### PR TITLE
Add runc containerd port

### PR DESCRIPTION
**Pull request by tussennet**
This contains building freebsd ports for runc and containerd, still with a lot of hacks. I didn't manage to put those together in one port, and technically both are standalone application although in pratice there is a strong connection between docker/containerd/runc.

With these ports its possible to manually run dockerd (given the PATH contains runc/containerd, those are not yet installed to standard PATH folders) and with dockerd running it's possible to use the standard docker port to connect to dockerd and do a build of a very simple dockerfile.

### CODE REVIEW

**Comment by decke** [comment]
You really made some good progress on docker. Do you need some help with the ports Makefiles / pkg-plist / install parts?

**Comment by tussennet** [comment]
Thanks, I think there will still be quiet some work coming from the runtime testing. I could use any help :) but I think the parts you name are easier for someone who is already familiar with creating ports. Currently I am skipping a lot of details to get a rudimentary version of docker running.

I think the following parts are needed for port integration (but if you think it could/should be differently please let me know):
- dockerd/runc/containerd should be installed into a normal binary directory
- dockerd should be run as a daemon
- dockerd should a runtime dependency on runc and containerd
- containerd is now build with `gmake` but should be buildable with gnu `make` (but freebsd `make` is different right?)
- runc is now build with plain go but also has it's own make file that is probably better to use

If you have any questions please let me know.

**Comment by joneum** [comment]
i just took the git repro from decke and tried to build it in poudriere: http://joneumbox.org/data/121amd64-ports/2020-11-08_17h29m20s/logs/errors/docker-freebsd-19.03.13.log

Is it better to continue working here, or here ? https://reviews.freebsd.org/D21570

**Comment by tussennet** [comment]
Thank you. The build log looks similar to what I have achieved locally. I think only the staging step needs to be improved to make it succesful.

I don't mind working in either place, but I am not familiar with phabricator. Is it hard to sync back from here to the other place? What would be the advantage of one over the other?

**Comment by joneum** [comment]
I can use the repro of Decke, and then synchronize it again with phabricator (which I did before).

If I see this correctly, many files have been patched, but the Makefile itself still needs to be edited?

**Comment by joneum** [comment]
ah, I just see that 2 additional ports need to be added: sysutils/runc and sysutils/containerd

**Comment by tussennet** [comment]
yes, both should be in PATH, also the make files to those two are very hacked together (just like most of my contribution :)), every improvement is welcome.

**Comment by joneum** [comment]
runc build fine after add pkg-plist. Ok, 1 line makes no sense here, but it works. This can be added to the Makefile later.

**Pull request merged**
